// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sm_repetition_algorithm.DAL.DataAccess;

#nullable disable

namespace sm_repetition_algorithm.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230623100635_AddedGroup")]
    partial class AddedGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Deck", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<int?>("DeckAndTermId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeckAndTermId");

                    b.HasIndex("GroupId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.DeckAndTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DeckId")
                        .HasColumnType("smallint");

                    b.Property<short>("TermId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("DeckAndTerms");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewWordAmount")
                        .HasColumnType("integer");

                    b.Property<int>("RepeatedWordAmount")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.RepetitionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Easiness")
                        .HasColumnType("real");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextPracticeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RepetitionNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<int>("TermId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Repetitions");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckAndTermId")
                        .HasColumnType("integer");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeckAndTermId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Deck", b =>
                {
                    b.HasOne("sm_repetition_algorithm.DAL.Entitis.DeckAndTerm", "DeckAndTerm")
                        .WithMany("Decs")
                        .HasForeignKey("DeckAndTermId");

                    b.HasOne("sm_repetition_algorithm.DAL.Entitis.Group", "Group")
                        .WithMany("Decks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckAndTerm");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Group", b =>
                {
                    b.HasOne("sm_repetition_algorithm.DAL.Entitis.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Term", b =>
                {
                    b.HasOne("sm_repetition_algorithm.DAL.Entitis.DeckAndTerm", "DeckAndTerm")
                        .WithMany("Terms")
                        .HasForeignKey("DeckAndTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeckAndTerm");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.DeckAndTerm", b =>
                {
                    b.Navigation("Decs");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.Group", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("sm_repetition_algorithm.DAL.Entitis.User", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
